/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include"lcd.h"
#include "rtc.h"
#include "timer.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
volatile extern int flag;
int main(void)
{
	RtcDate_t dt;
	char str[50];
	dt.date = 30;
	dt.month = 9;
	dt.year = 25;
	dt.weekday = 2;
	RtcTime_t tm;
	tm.hr=21;
	tm.min=14;
	tm.sec=16;
	LcdInit();
	TimerInit(1000);
	RtcInit(&dt,&tm);
	while(1)
	{
		if(flag)
		{
			sprintf(str,"%d-%d-%d-%d %d-%d-%d",dt.date,dt.month,dt.year,dt.weekday,tm.hr,tm.min,tm.sec);
			LcdPuts(LCD_LINE1,str);
			flag=0;
		}
	}
}

