/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "accel.h"
#include "led.h"
#include "lcd.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	AccelData_t accel;

	led_init(12);
	led_init(13);
	led_init(14);
	led_init(15);
	AccelInit();
	while(AccelWaitForChange()) {
		AccelRead(&accel);
		if(accel.x > 3000)
		{
			led_on(14);
		}
		else
		{
			led_off(14);
		}
		if(accel.x < -3000)
		{
			led_on(12);
		}
		else
		{
			led_off(12);
		}
		if(accel.y > 3000)
		{
			led_on(13);

		}
		else
		{
			led_off(13);
		}
		if(accel.y < -3000)
		{
			led_on(15);
		}
		else
		{
			led_off(15);
		}
	}
}

