/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "led.h"
#include "systick.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


volatile extern uint32_t xTicks;
int main(void)
{
	LedInit(LED_GREEN);
	LedInit(LED_ORANGE);
	LedInit(LED_RED);
	LedInit(LED_BLUE);
	systick_init();
	while(1)
	{
		LedToggle(LED_GREEN);
		SysTick_DelayMs(1000);
		LedToggle(LED_ORANGE);
		SysTick_DelayMs(1000);
		LedToggle(LED_RED);
		SysTick_DelayMs(1000);
		LedToggle(LED_BLUE);
		SysTick_DelayMs(1000);
	}
	return 0;


}

